#!/usr/bin/python
# _*_ coding:utf-8 _*_

import sys
import signal
import urwid
from eayunos_console_common import ConfigTab, TabNetwork
from eayunos_console_node import TabHostedEngine, TabNFS

def handler(signum, frame):
    sys.exit()

signal.signal(signal.SIGINT, handler)

palette = [
    ('buttn','black','dark cyan'),
    ('buttnf','white','dark blue','bold'),
]
loop = urwid.MainLoop(None, palette, pop_ups=True)
config_tab_list = [
    TabNetwork(loop),
    TabHostedEngine(loop),
    TabNFS(loop),
]
loop.widget = ConfigTab(config_tab_list)

if __name__ == '__main__':
   loop.run()
